name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployed artifact
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Result of deployment
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secrets:
    #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
